FROM debian:stable-slim AS build
COPY requirements.txt /requirements.txt
RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes python3-venv && \
    python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install --disable-pip-version-check -r /requirements.txt

FROM gcr.io/distroless/python3-debian10
COPY --from=build /venv /venv
COPY /app/ /app
EXPOSE 8000
WORKDIR /app
ENTRYPOINT ["/venv/bin/python3", "main.py"]